//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112141
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public department()
        {
            this.employee1 = new HashSet<employee>();
        }

        public department(string name, int ep_id)
        {
            this.name = name;
            this.ep_id = ep_id;
        }

        public department(int dp_id, string name, int? ep_id)
        {
            this.dp_id = dp_id;
            this.name = name;
            this.ep_id = ep_id;
        }

        public int dp_id { get; set; }
        public string name { get; set; }
        public Nullable<int> ep_id { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee> employee1 { get; set; }
    }
}
