//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS201724112141
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int eq_id { get; set; }
        public string name { get; set; }
        public string specifications { get; set; }
        public string picture { get; set; }
        public double price { get; set; }
        public System.DateTime date { get; set; }
        public string location { get; set; }
        public int ep_id { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
